import * as AntSql from '../ant';
import { AntSqlManager } from '../api/ant-sql-manager';
import { AutoGeneratedStrategyMode } from '../model/auto-generation-strategy-mode';
import { KnexDriver } from '../persistence/secondary/knex-driver';
import { Test } from '@antjs/ant-js/build/testapi/api/test';

export class AntTest implements Test {
  public performTests(): void {
    describe('AntTest', () => {
      this._itMustExportTypes();
    });
  }

  private _itMustExportTypes(): void {
    it('mustExportTypes', () => {
      expect(AntSql.AntSqlManager).toBe(AntSqlManager);
      expect(AntSql.AutoGeneratedStrategyMode).toBe(AutoGeneratedStrategyMode);
      expect(AntSql.KnexDriver).toBe(KnexDriver);
    });
  }
}
