import { Test } from '@antjs/ant-js/build/testapi/api/test';
import * as AntJs from '../ant';
import { AntSqlManager } from '../api/ant-sql-manager';
import { AntSqlModel } from '../model/ant-sql-model';
import { AutoGeneratedStrategyMode } from '../model/auto-generation-strategy-mode';
import { KnexDriver } from '../persistence/secondary/knex-driver';

export class AntTest implements Test {
  public performTests() {
    describe('AntTest', () => {
      this._itMustExportTypes();
    });
  }

  private _itMustExportTypes(): void {
    it('mustExportTypes', () => {
      expect(AntJs.AntSqlManager).toBe(AntSqlManager);
      expect(AntJs.AntSqlModel).toBe(AntSqlModel);
      expect(AntJs.AutoGeneratedStrategyMode).toBe(AutoGeneratedStrategyMode);
      expect(AntJs.KnexDriver).toBe(KnexDriver);
    });
  }
}
