version: '3'
services:
  ant_lib:
    build: .
    command: ["npm", "run", "ci"]
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}
networks:
  ant:
    driver: bridge
