import { Entity } from '@antjs/ant-js/src/model/entity';
import { AntSqlSecondaryEntityManager } from './AntSqlSecondaryEntityManager';

export class AntMySqlSecondaryEntityManager<TEntity extends Entity>
  extends AntSqlSecondaryEntityManager<TEntity> {

  /**
   * @inheritdoc
   */
  public mInsert(entities: TEntity[]): Promise<any> {
    const autoGeneratedColumn = this.model.getAutoGeneratedColumn();
    if (null == autoGeneratedColumn) {
      return super.mInsert(entities);
    } else {
      return this
        ._helper
        .mInsertOnAutoincrementWithNoMultipleReturning(
          entities,
          autoGeneratedColumn,
        );
    }
  }
}
