import * as Knex from 'knex';
import { Entity } from '@antjs/ant-js';
import { SqlColumn } from '../../model/sql-column';
import { SqlModel } from '../../model/sql-model';

export class SecondaryEntityManagerHelper<TEntity extends Entity> {
  /**
   * DB Connection.
   */
  protected _dbConnection: Knex;
  /**
   * Model to manage.
   */
  protected _model: SqlModel<TEntity>;

  /**
   * Creates a new secondary entity manager helper.
   * @param model Model to manage.
   * @param dbConnection Knex DB Connection.
   */
  public constructor(model: SqlModel<TEntity>, dbConnection: Knex) {
    this._dbConnection = dbConnection;
    this._model = model;
  }

  public mInsertOnAutoincrementWithNoMultipleReturning(
    entities: TEntity[],
    autoGeneratedColumn: SqlColumn,
  ): Promise<any> {
    if (0 === entities.length) {
      return new Promise((resolve) => resolve());
    }
    return this._dbConnection.transaction((transaction) => {
      const queries = new Array<Knex.QueryBuilder>();
      for (const entity of entities) {
        queries.push(
          this._dbConnection
            .insert(this._model.entityToSecondary(entity))
            .into(this._model.tableName)
            .transacting(transaction),
        );
      }
      Promise.all(queries)
        .then((values) => {
          return transaction.commit().then(() => {
            for (let i = 0; i < entities.length; ++i) {
              (entities[i] as Entity)[autoGeneratedColumn.entityAlias] = values[i][0];
            }
          });
        })
        .catch(transaction.rollback);
    });
  }
}
