import { Model } from '@antjs/ant-js';
import { ApiSqlColumn } from './api-sql-column';

export interface IAntSqlModel extends Model {
  /**
   * Map of table columns, including the id;
   * The key of the map is the alias of the column in the entities managed.
   * The value of the map is the column info.
   */
  columns: Iterable<ApiSqlColumn>;
  /**
   * SQL table name.
   */
  tableName: string;
  /**
   * Gets the auto generated column of the model.
   * @returns Auto generated column of the model or null if no column is auto generated.
   */
  getAutoGeneratedColumn(): ApiSqlColumn;

  /**
   * Gets a column by its alias
   */
  getColumn(alias: string): ApiSqlColumn;
}
