import { AutoGeneratedStrategyMode } from './auto-generation-strategy-mode';
import { SqlType } from './sql-type';

export interface SqlColumn {
  /**
   * Auto generation strategy.
   */
  readonly autoGenerationStrategy?: AutoGeneratedStrategyMode;
  /**
   * Alias of the column in the entities managed.
   */
  readonly entityAlias: string;
  /**
   * Name of the column.
   */
  readonly sqlName: string;
  /**
   * Type of the column.
   */
  readonly type: SqlType;
}
