import { AutoGeneratedStrategyMode } from './auto-generation-strategy-mode';

export interface SqlColumn {
  /**
   * Auto generation strategy.
   */
  autoGenerationStrategy?: AutoGeneratedStrategyMode;
  /**
   * Alias of the column in the entities managed.
   */
  entityAlias: string;
  /**
   * Name of the column.
   */
  sqlName: string;
}
