import { Model } from '@antjs/ant-js';
import { SqlColumn } from './sql-column';

export interface SqlModel extends Model {
  /**
   * Map of table columns, including the id;
   * The key of the map is the alias of the column in the entities managed.
   * The value of the map is the column info.
   */
  columns: Iterable<SqlColumn>;
  /**
   * SQL table name.
   */
  tableName: string;
  /**
   * Gets the auto generated column of the model.
   * @returns Auto generated column of the model or null if no column is auto generated.
   */
  getAutoGeneratedColumn(): SqlColumn;

  /**
   * Gets a column by its alias
   */
  getColumn(alias: string): SqlColumn;
}
