import { AutoGeneratedStrategyMode } from './auto-generation-strategy-mode';
import { SqlType } from './sql-type';

export interface SqlColumn {
  /**
   * Auto generation strategy.
   */
  autoGenerationStrategy?: AutoGeneratedStrategyMode;
  /**
   * Alias of the column in the entities managed.
   */
  entityAlias: string;
  /**
   * Name of the column.
   */
  sqlName: string;
  /**
   * Type of the column.
   */
  type: SqlType;
}
